// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Actualizacion
    {
        public int IdAct { get; set; }
        public string NumInv { get; set; }
        public string NumSerie { get; set; }
        public string Descripcion { get; set; }
        public DateTime? Fecha { get; set; }

        public virtual Computadorafinal NumInvNavigation { get; set; }
    }
}