// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class CantDisc
    {
        public int IdCant { get; set; }
        public string NumInv { get; set; }
        public int? IdDisco { get; set; }

        public virtual DiscoDuro IdDiscoNavigation { get; set; }
        public virtual Computadorafinal NumInvNavigation { get; set; }
    }
}