// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Categoria
    {
        public Categoria()
        {
            CatMar = new HashSet<CatMar>();
        }

        public int IdCategoria { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<CatMar> CatMar { get; set; }
    }
}