// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class CpuGenerico
    {
        public int IdCpu { get; set; }
        public int FTcpu { get; set; }
        public int FMarcaCpu { get; set; }
        public string Modelo { get; set; }
        public string Descripcion { get; set; }
        public int? FTipoRam { get; set; }
        public int? IdGabinete { get; set; }

        public virtual Marca FMarcaCpuNavigation { get; set; }
        public virtual TipoCpu FTcpuNavigation { get; set; }
        public virtual Ram FTipoRamNavigation { get; set; }
        public virtual Gabinete IdGabineteNavigation { get; set; }
    }
}