// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class CpuTipoMod
    {
        public int IdTipoMod { get; set; }
        public int? IdTcpu { get; set; }
        public int? IdModcpu { get; set; }
        public string Nucleos { get; set; }

        public virtual ModeloCpu IdModcpuNavigation { get; set; }
        public virtual TipoCpu IdTcpuNavigation { get; set; }
    }
}