// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Estatus
    {
        public Estatus()
        {
            Computadorafinal = new HashSet<Computadorafinal>();
        }

        public int IdEstatus { get; set; }
        public string Estado { get; set; }

        public virtual ICollection<Computadorafinal> Computadorafinal { get; set; }
    }
}