// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Evidencia
    {
        public int IdEvidencia { get; set; }
        public string Evidencia1 { get; set; }
        public string NumInv { get; set; }

        public virtual Computadorafinal NumInvNavigation { get; set; }
    }
}