// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Gabinete
    {
        public Gabinete()
        {
            CpuGenerico = new HashSet<CpuGenerico>();
        }

        public int IdGabinete { get; set; }
        public string Modelo { get; set; }
        public string TipoForma { get; set; }
        public int FMarca { get; set; }

        public virtual Marca FMarcaNavigation { get; set; }
        public virtual ICollection<CpuGenerico> CpuGenerico { get; set; }
    }
}