// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Marca
    {


        public int IdMarca { get; set; }
        public string Marca1 { get; set; }
        public short IdComponente { get; set; }
        public string Extra { get; set; }

        public virtual ICollection<CatMar> CatMar { get; set; }
        public virtual ICollection<CpuGenerico> CpuGenerico { get; set; }
        public virtual ICollection<DiscoDuro> DiscoDuro { get; set; }
        public virtual ICollection<Gabinete> Gabinete { get; set; }
        public virtual ICollection<ModeloCpu> ModeloCpu { get; set; }
        public virtual ICollection<Monitor> Monitor { get; set; }
        public virtual ICollection<Mouse> Mouse { get; set; }
        public virtual ICollection<Teclado> Teclado { get; set; }
    }
}