// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class ModeloCpu
    {
        //public ModeloCpu()
        //{
        //    CpuTipoMod = new HashSet<CpuTipoMod>();
        //}

        public int IdModcpu { get; set; }
        public string ModeloCpu1 { get; set; }
        public int FMarca { get; set; }

        public virtual Marca FMarcaNavigation { get; set; }
        public virtual ICollection<CpuTipoMod> CpuTipoMod { get; set; }
    }
}