// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Monitor
    {
        public int IdMonitor { get; set; }
        public int? FMarcam { get; set; }
        public string Conectores { get; set; }
        public string Tamano { get; set; }

        public virtual Marca FMarcamNavigation { get; set; }
    }
}