// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Mouse
    {
        public int IdMouse { get; set; }
        public int? FMarcamouse { get; set; }
        public string Conector { get; set; }

        public virtual Marca FMarcamouseNavigation { get; set; }
    }
}