// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Ram
    {
        public Ram()
        {
            CpuGenerico = new HashSet<CpuGenerico>();
        }

        public int IdRam { get; set; }
        public short Capacidad { get; set; }
        public string Velocidad { get; set; }
        public int FTipoR { get; set; }

        public virtual TipoRam FTipoRNavigation { get; set; }
        public virtual ICollection<CpuGenerico> CpuGenerico { get; set; }
    }
}