// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class TipoCpu
    {
        public TipoCpu()
        {
            CpuGenerico = new HashSet<CpuGenerico>();
            CpuTipoMod = new HashSet<CpuTipoMod>();
        }

        public int IdTcpu { get; set; }
        public string Tipo { get; set; }
        public string Familia { get; set; }
        public string Velocidad { get; set; }
        public string Extra { get; set; }

        public virtual ICollection<CpuGenerico> CpuGenerico { get; set; }
        public virtual ICollection<CpuTipoMod> CpuTipoMod { get; set; }
    }
}