// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class TipoRam
    {
        public TipoRam()
        {
            Ram = new HashSet<Ram>();
        }

        public int IdTipoRam { get; set; }
        public string Tipo { get; set; }
        public string Extra { get; set; }

        public virtual ICollection<Ram> Ram { get; set; }
    }
}