// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace c_entidades
{
    public partial class Ubicacion
    {
        public string NumInv { get; set; }
        public string NombreLaboratorio { get; set; }

        public virtual Laboratorio NombreLaboratorioNavigation { get; set; }
        public virtual Computadorafinal NumInvNavigation { get; set; }
    }
}